#ifndef MESSAGE_BIT_CODE_H
#define MESSAGE_BIT_CODE_H

#define STOP 0x00
#define MOVE_FORWARD 0x01
#define MOVE_BACKWARD 0x10
#define TURN_LEFT 0x17
#define TURN_RIGHT 0x19
#define MOVE_FORWARD_LEFT 0x11
#define MOVE_FORWARD_RIGHT 0x12
#define MOVE_BACKWARD_LEFT 0x13
#define MOVE_BACKWARD_RIGHT 0x14
#define SPIN_CLOCKWISE 0x15
#define SPIN_COUNTERCLOCKWISE 0x16
#define TURN_LEFT_REVERSE 0x18
#define TURN_RIGHT_REVERSE 0x20





#endif